// reference/nuxt-vuetify/components/EditorToolbar.vue
<template>
  <v-toolbar density="compact" flat class="border-b px-2">
    <v-btn-toggle
      :model-value="store.activeTool"
      mandatory
      density="compact"
      color="primary"
      variant="outlined"
      divided
      @update:model-value="store.setTool($event)"
    >
      <v-btn v-for="t in tools" :key="t.value" :value="t.value" size="small">
        <v-icon :icon="t.icon" size="18" class="mr-1" />
        <span class="text-caption">{{ t.label }}</span>
      </v-btn>
    </v-btn-toggle>

    <v-spacer />

    <v-btn icon size="small" variant="text" :disabled="!store.undoStack.length" @click="store.undo()">
      <v-icon icon="mdi-undo" />
      <v-tooltip activator="parent" location="bottom">Undo (Ctrl+Z)</v-tooltip>
    </v-btn>
    <v-btn icon size="small" variant="text" :disabled="!store.redoStack.length" @click="store.redo()">
      <v-icon icon="mdi-redo" />
      <v-tooltip activator="parent" location="bottom">Redo (Ctrl+Y)</v-tooltip>
    </v-btn>

    <v-divider vertical class="mx-2" />

    <v-btn icon size="small" variant="text" @click="store.setZoom(store.zoomLevel + 0.1)">
      <v-icon icon="mdi-magnify-plus-outline" />
    </v-btn>
    <span class="text-caption mx-1">{{ Math.round(store.zoomLevel * 100) }}%</span>
    <v-btn icon size="small" variant="text" @click="store.setZoom(store.zoomLevel - 0.1)">
      <v-icon icon="mdi-magnify-minus-outline" />
    </v-btn>

    <v-divider vertical class="mx-2" />

    <v-btn
      size="small"
      variant="text"
      color="warning"
      prepend-icon="mdi-delete-sweep-outline"
      @click="store.clearCurrentSide()"
    >
      Clear Side
    </v-btn>
  </v-toolbar>
</template>

<script setup lang="ts">
import { useConfiguratorStore } from '~/stores/configurator';

const store = useConfiguratorStore();

const tools = [
  { value: 'hole', icon: 'mdi-circle-outline', label: 'Hole (V)' },
  { value: 'rect', icon: 'mdi-rectangle-outline', label: 'Rect (H)' },
  { value: 'opening', icon: 'mdi-square-rounded-outline', label: 'Opening (O)' },
  { value: 'move', icon: 'mdi-cursor-move', label: 'Move (M)' },
];
</script>

// reference/nextjs-daisyui/src/components/editor-toolbar.tsx
'use client';

import { useConfiguratorStore } from '@/lib/configurator-store';
import type { ToolType } from '@/lib/types';

const TOOLS: { value: ToolType; label: string; icon: string }[] = [
  { value: 'hole', icon: '○', label: 'Hole (V)' },
  { value: 'rect', icon: '□', label: 'Rect (H)' },
  { value: 'opening', icon: '▢', label: 'Opening (O)' },
  { value: 'move', icon: '✥', label: 'Move (M)' },
];

export function EditorToolbar() {
  const { activeTool, setTool, undo, redo, undoStack, redoStack, zoomLevel, setZoom, clearCurrentSide } =
    useConfiguratorStore();

  return (
    <div className="flex items-center gap-2 px-3 py-1 border-b border-base-300 bg-base-100">
      {/* Tool toggle */}
      <div className="join">
        {TOOLS.map(t => (
          <button
            key={t.value}
            className={`join-item btn btn-sm ${activeTool === t.value ? 'btn-primary' : 'btn-ghost'}`}
            onClick={() => setTool(t.value)}
          >
            <span className="mr-1">{t.icon}</span>{t.label}
          </button>
        ))}
      </div>

      <div className="flex-1" />

      {/* Undo / Redo */}
      <div className="tooltip tooltip-bottom" data-tip="Undo (Ctrl+Z)">
        <button className="btn btn-ghost btn-sm btn-square" disabled={!undoStack.length} onClick={undo}>↩</button>
      </div>
      <div className="tooltip tooltip-bottom" data-tip="Redo (Ctrl+Y)">
        <button className="btn btn-ghost btn-sm btn-square" disabled={!redoStack.length} onClick={redo}>↪</button>
      </div>

      <div className="divider divider-horizontal mx-0" />

      {/* Zoom */}
      <button className="btn btn-ghost btn-sm btn-square" onClick={() => setZoom(zoomLevel + 0.1)}>🔍+</button>
      <span className="text-xs font-mono w-10 text-center">{Math.round(zoomLevel * 100)}%</span>
      <button className="btn btn-ghost btn-sm btn-square" onClick={() => setZoom(zoomLevel - 0.1)}>🔍−</button>

      <div className="divider divider-horizontal mx-0" />

      {/* Clear */}
      <button className="btn btn-ghost btn-sm text-warning gap-1" onClick={clearCurrentSide}>
        🗑 Clear Side
      </button>
    </div>
  );
}
