// reference/nuxt-vuetify/components/EditorFooter.vue
<template>
  <v-toolbar density="compact" flat class="border-t px-3">
    <v-icon icon="mdi-information-outline" size="16" class="mr-2 text-grey" />
    <span class="text-caption text-grey">
      {{ store.currentElements.length }} element{{ store.currentElements.length !== 1 ? 's' : '' }} ·
      Grid {{ SNAP_GRID }}mm ·
      Zoom {{ Math.round(store.zoomLevel * 100) }}%
    </span>
    <v-spacer />
    <span class="text-caption text-grey-darken-1">
      <kbd class="text-caption">V</kbd> Hole
      <kbd class="text-caption ml-2">H</kbd> Rect
      <kbd class="text-caption ml-2">O</kbd> Opening
      <kbd class="text-caption ml-2">M</kbd> Move
      <kbd class="text-caption ml-2">Del</kbd> Delete
    </span>
  </v-toolbar>
</template>

<script setup lang="ts">
import { useConfiguratorStore } from '~/stores/configurator';
import { SNAP_GRID } from '~/utils/constants';
const store = useConfiguratorStore();
</script>

<style scoped>
kbd {
  background: rgba(0,0,0,0.06);
  border-radius: 3px;
  padding: 1px 4px;
  font-family: inherit;
}
</style>

// reference/nextjs-daisyui/src/components/editor-footer.tsx
'use client';

import { useConfiguratorStore } from '@/lib/configurator-store';
import { SNAP_GRID } from '@/lib/constants';

export function EditorFooter() {
  const { sideElements, currentSide, zoomLevel } = useConfiguratorStore();
  const count = sideElements[currentSide].length;

  return (
    <div className="flex items-center justify-between px-3 py-1 border-t border-base-300 bg-base-100 text-xs text-base-content/50">
      <span>
        ℹ {count} element{count !== 1 ? 's' : ''} · Grid {SNAP_GRID}mm · Zoom {Math.round(zoomLevel * 100)}%
      </span>
      <span className="flex gap-2">
        <kbd>V</kbd> Hole
        <kbd>H</kbd> Rect
        <kbd>O</kbd> Opening
        <kbd>M</kbd> Move
        <kbd>Del</kbd> Delete
      </span>
    </div>
  );
}
