// reference/nuxt-vuetify/pages/configure.vue
<template>
  <v-layout class="fill-height">
    <v-app-bar density="compact" flat class="border-b">
      <AppHeader />
    </v-app-bar>

    <v-main class="bg-background">
      <v-container fluid class="pa-0 fill-height">
        <v-row no-gutters class="fill-height">
          <!-- Left sidebar: Side pills -->
          <v-col cols="auto" class="d-flex align-center justify-center" style="width:64px">
            <SidePills />
          </v-col>

          <!-- Center area: toolbar + 3D + editor -->
          <v-col class="d-flex flex-column fill-height">
            <EditorToolbar />

            <div class="flex-grow-1 d-flex" style="min-height:0">
              <!-- 3D preview -->
              <div class="d-flex align-center justify-center" style="width:280px;min-width:200px">
                <Cabinet3DPreview />
              </div>

              <!-- 2D Panel editor -->
              <div class="flex-grow-1 d-flex flex-column" style="min-width:0">
                <PanelEditor />
                <EditorFooter />
              </div>
            </div>
          </v-col>

          <!-- Right sidebar: properties + element list -->
          <v-col cols="auto" style="width:280px" class="border-l d-flex flex-column fill-height bg-surface">
            <PropertiesPanel />
            <v-divider />
            <ElementList />
          </v-col>
        </v-row>
      </v-container>
    </v-main>
  </v-layout>
</template>

<script setup lang="ts">
import { useKeyboardShortcuts } from '~/composables/useKeyboardShortcuts';
useKeyboardShortcuts();
</script>

// reference/nextjs-daisyui/src/app/configure/page.tsx
'use client';

import { AppHeader } from '@/components/app-header';
import { SidePills } from '@/components/side-pills';
import { EditorToolbar } from '@/components/editor-toolbar';
import { Cabinet3DPreview } from '@/components/cabinet-3d-preview';
import { PanelEditor } from '@/components/panel-editor';
import { PropertiesPanel } from '@/components/properties-panel';
import { ElementList } from '@/components/element-list';
import { EditorFooter } from '@/components/editor-footer';
import { Toast } from '@/components/toast';
import { useKeyboardShortcuts } from '@/hooks/use-keyboard-shortcuts';

export default function ConfigurePage() {
  useKeyboardShortcuts();

  return (
    <div className="flex flex-col h-screen">
      {/* Header */}
      <AppHeader />

      {/* Body */}
      <div className="flex flex-1 min-h-0">
        {/* Left: side pills */}
        <div className="flex items-center justify-center w-16 border-r border-base-300 bg-base-100">
          <SidePills />
        </div>

        {/* Center */}
        <div className="flex flex-col flex-1 min-w-0">
          <EditorToolbar />
          <div className="flex flex-1 min-h-0">
            {/* 3D */}
            <div className="flex items-center justify-center bg-base-100 border-r border-base-300"
              style={{ width: 280, minWidth: 200 }}>
              <Cabinet3DPreview />
            </div>
            {/* 2D editor */}
            <div className="flex flex-col flex-1 min-w-0">
              <PanelEditor />
              <EditorFooter />
            </div>
          </div>
        </div>

        {/* Right sidebar */}
        <div className="flex flex-col w-72 border-l border-base-300 bg-base-100">
          <PropertiesPanel />
          <div className="divider my-0 px-3" />
          <ElementList />
        </div>
      </div>

      <Toast />
    </div>
  );
}
