// reference/nextjs-daisyui/src/components/cabinet-3d-preview.tsx
'use client';

import { useConfiguratorStore } from '@/lib/configurator-store';
import { CABINETS, SIDES, SIDE_ROTATIONS } from '@/lib/constants';
import type { Side, PanelElement } from '@/lib/types';

const S = 0.28;

export function Cabinet3DPreview() {
  const { currentCabinet, currentSide, sideElements, setSide } = useConfiguratorStore();
  const cab = CABINETS[currentCabinet];
  const cw = cab.w * S, ch = cab.h * S, cd = cab.d * S;
  const rot = SIDE_ROTATIONS[currentSide];

  const faceStyles: Record<Side, string> = {
    front:  `width:${cw}px;height:${ch}px;transform:translateZ(${cd/2}px)`,
    back:   `width:${cw}px;height:${ch}px;transform:rotateY(180deg) translateZ(${cd/2}px)`,
    left:   `width:${cd}px;height:${ch}px;transform:rotateY(-90deg) translateZ(${cw/2}px)`,
    right:  `width:${cd}px;height:${ch}px;transform:rotateY(90deg) translateZ(${cw/2}px)`,
    top:    `width:${cw}px;height:${cd}px;transform:rotateX(90deg) translateZ(${ch/2}px)`,
    bottom: `width:${cw}px;height:${cd}px;transform:rotateX(-90deg) translateZ(${ch/2}px)`,
  };

  function elPos(el: PanelElement, side: Side) {
    const fw = ['left','right'].includes(side) ? cab.d : cab.w;
    const fh = ['top','bottom'].includes(side) ? cab.d : cab.h;
    return {
      left: `${(el.x/fw)*100}%`, top: `${(el.y/fh)*100}%`,
      width: `${(el.w/fw)*100}%`, height: `${(el.h/fh)*100}%`,
      borderRadius: el.type === 'hole' ? '50%' : '2px',
      background: el.type === 'hole' ? '#4f46e5' : el.type === 'rect' ? '#06b6d4' : '#f59e0b',
    };
  }

  return (
    <div style={{ perspective: 600 }} className="flex items-center justify-center w-full h-full">
      <div
        className="relative preserve-3d side-transition"
        style={{ width: cw, height: ch, transform: `rotateX(${rot.x}deg) rotateY(${rot.y}deg)` }}
      >
        {SIDES.map(side => (
          <div
            key={side}
            className={`absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex items-center justify-center cursor-pointer border transition-colors
              ${side === currentSide ? 'border-primary bg-primary/15' : 'border-primary/20 bg-primary/5 hover:bg-primary/10'}`}
            style={{ ...parseStyle(faceStyles[side]), backfaceVisibility: 'visible' }}
            onClick={() => setSide(side)}
          >
            <span className="text-[10px] uppercase tracking-widest text-primary/50 pointer-events-none">{side}</span>
            {sideElements[side].map(el => (
              <div key={el.id} className="absolute opacity-80 pointer-events-none" style={elPos(el, side)} />
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}

function parseStyle(s: string): Record<string, string> {
  const o: Record<string, string> = {};
  s.split(';').forEach(p => {
    const [k, v] = p.split(':').map(x => x.trim());
    if (k && v) o[k.replace(/-([a-z])/g, (_, c) => c.toUpperCase())] = v;
  });
  return o;
}

// reference/nuxt-vuetify/components/Cabinet3DPreview.vue
<template>
  <div class="cabinet-3d-wrap">
    <div class="cabinet-3d" :style="cubeStyle">
      <div
        v-for="side in SIDES"
        :key="side"
        class="face"
        :class="[`face-${side}`, { 'face-active': side === store.currentSide }]"
        :style="faceStyle(side)"
        @click="store.setSide(side)"
      >
        <span class="face-label">{{ side }}</span>
        <div
          v-for="el in store.sideElements[side]"
          :key="el.id"
          class="face-el"
          :style="elStyle(el, side)"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useConfiguratorStore } from '~/stores/configurator';
import { CABINETS, SIDES, SIDE_ROTATIONS } from '~/utils/constants';
import type { Side, PanelElement } from '~/utils/types';

const store = useConfiguratorStore();

const S = 0.28; // scale factor

const cab = computed(() => CABINETS[store.currentCabinet]);
const cw = computed(() => cab.value.w * S);
const ch = computed(() => cab.value.h * S);
const cd = computed(() => cab.value.d * S);

const cubeStyle = computed(() => {
  const rot = SIDE_ROTATIONS[store.currentSide];
  return {
    width: `${cw.value}px`,
    height: `${ch.value}px`,
    transform: `rotateX(${rot.x}deg) rotateY(${rot.y}deg)`,
  };
});

function faceStyle(side: Side) {
  const w = cw.value, h = ch.value, d = cd.value;
  const map: Record<Side, string> = {
    front:  `width:${w}px;height:${h}px;transform:translateZ(${d / 2}px)`,
    back:   `width:${w}px;height:${h}px;transform:rotateY(180deg) translateZ(${d / 2}px)`,
    left:   `width:${d}px;height:${h}px;transform:rotateY(-90deg) translateZ(${w / 2}px)`,
    right:  `width:${d}px;height:${h}px;transform:rotateY(90deg) translateZ(${w / 2}px)`,
    top:    `width:${w}px;height:${d}px;transform:rotateX(90deg) translateZ(${h / 2}px)`,
    bottom: `width:${w}px;height:${d}px;transform:rotateX(-90deg) translateZ(${h / 2}px)`,
  };
  return map[side];
}

function elStyle(el: PanelElement, side: Side) {
  const fw = ['left', 'right'].includes(side) ? cab.value.d : cab.value.w;
  const fh = ['top', 'bottom'].includes(side) ? cab.value.d : cab.value.h;
  return {
    left: `${(el.x / fw) * 100}%`,
    top: `${(el.y / fh) * 100}%`,
    width: `${(el.w / fw) * 100}%`,
    height: `${(el.h / fh) * 100}%`,
    borderRadius: el.type === 'hole' ? '50%' : '2px',
    background: el.type === 'hole' ? '#1565C0' : el.type === 'rect' ? '#00ACC1' : '#F9A825',
  };
}
</script>

<style scoped>
.cabinet-3d-wrap {
  perspective: 600px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
}
.cabinet-3d {
  position: relative;
  transform-style: preserve-3d;
  transition: transform 0.5s ease;
}
.face {
  position: absolute;
  top: 50%; left: 50%;
  transform-origin: center;
  margin-top: calc(-50%);
  margin-left: calc(-50%);
  backface-visibility: visible;
  border: 1px solid rgba(21,101,192,0.25);
  background: rgba(21,101,192,0.06);
  cursor: pointer;
  transition: background 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
}
.face:hover { background: rgba(21,101,192,0.12); }
.face-active { border-color: rgb(21,101,192); background: rgba(21,101,192,0.15); }
.face-label {
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 1px;
  color: rgba(21,101,192,0.6);
  pointer-events: none;
}
.face-el {
  position: absolute;
  opacity: 0.85;
  pointer-events: none;
}
</style>
