// reference/nuxt-app/components/AppToast.vue
<template>
  <div
    :class="[
      'fixed bottom-6 left-1/2 -translate-x-1/2 bg-gray-900 text-white px-5 py-2.5 rounded-[10px] text-sm font-medium shadow-md flex items-center gap-2 transition-transform duration-300 z-[1000]',
      store.toastMessage ? 'translate-y-0' : 'translate-y-20'
    ]"
  >
    <span class="text-base">{{ store.toastIcon }}</span>
    <span>{{ store.toastMessage }}</span>
  </div>
</template>

<script setup lang="ts">
const store = useConfiguratorStore();

watch(() => store.toastMessage, (msg) => {
  if (msg) {
    setTimeout(() => store.clearToast(), 2200);
  }
});
</script>

// reference/nextjs-shadcn-babylon/components/app-toast.tsx
'use client';

import { useEffect } from 'react';
import { useConfiguratorStore } from '@/store/configurator-store';
import { cn } from '@/lib/utils';
import { CheckCircle2, AlertCircle, Info, X } from 'lucide-react';

export default function AppToast() {
  const { toastMessage, toastIcon, clearToast } = useConfiguratorStore();

  useEffect(() => {
    if (!toastMessage) return;
    const timer = setTimeout(clearToast, 3000);
    return () => clearTimeout(timer);
  }, [toastMessage, clearToast]);

  if (!toastMessage) return null;

  const iconMap: Record<string, React.ReactNode> = {
    '✓': <CheckCircle2 className="h-4 w-4" />,
    '🛒': <CheckCircle2 className="h-4 w-4" />,
    '↩': <Info className="h-4 w-4" />,
    '↪': <Info className="h-4 w-4" />,
    '🗑': <AlertCircle className="h-4 w-4" />,
  };

  return (
    <div className={cn(
      'fixed bottom-6 right-6 z-50 flex items-center gap-2 px-4 py-3 rounded-lg shadow-lg border text-sm',
      'bg-card text-card-foreground animate-in slide-in-from-bottom-4 fade-in duration-300'
    )}>
      <span className="text-primary">{iconMap[toastIcon] || <Info className="h-4 w-4" />}</span>
      <span>{toastMessage}</span>
      <button onClick={clearToast} className="ml-2 text-muted-foreground hover:text-foreground">
        <X className="h-3.5 w-3.5" />
      </button>
    </div>
  );
}
