// reference/sveltekit-app/src/lib/components/EditorFooter.svelte
<script lang="ts">
  import { configurator } from '$lib/stores/configurator';
  import { formatDimensions, CABINETS } from '$lib/constants';

  const { cabinet, currentSide, zoom, currentElements } = configurator;

  const zoomLevels = [0.5, 0.75, 1, 1.25, 1.5, 2];
</script>

<div class="h-9 bg-white border-t border-slate-200 flex items-center px-4 justify-between text-xs text-slate-500 shrink-0">
  <div class="flex items-center gap-4">
    <span>{CABINETS[$cabinet].label}</span>
    <span class="text-slate-300">|</span>
    <span class="capitalize">{$currentSide}</span>
    <span class="text-slate-300">|</span>
    <span>{formatDimensions($cabinet)}</span>
    <span class="text-slate-300">|</span>
    <span>{$currentElements.length} element{$currentElements.length !== 1 ? 's' : ''}</span>
  </div>

  <div class="flex items-center gap-2">
    <span>Zoom</span>
    <select
      class="border border-slate-300 rounded px-1 py-0.5 text-xs"
      value={$zoom}
      on:change={(e) => configurator.setZoom(Number((e.target).value))}
    >
      {#each zoomLevels as z}
        <option value={z}>{Math.round(z * 100)}%</option>
      {/each}
    </select>
  </div>
</div>

// reference/nextjs-shadcn-babylon/components/editor-footer.tsx
'use client';

import { useConfiguratorStore } from '@/store/configurator-store';
import { CABINETS, formatDimensions } from '@/lib/constants';
import { Separator } from '@/components/ui/separator';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const ZOOM_LEVELS = [0.5, 0.75, 1, 1.25, 1.5, 2];

export default function EditorFooter() {
  const { currentCabinet, currentSide, zoomLevel, setZoom, currentElements } = useConfiguratorStore();
  const els = currentElements();

  return (
    <div className="h-9 border-t bg-card flex items-center px-4 justify-between text-xs text-muted-foreground shrink-0">
      <div className="flex items-center gap-3">
        <span className="font-medium">{CABINETS[currentCabinet].label}</span>
        <Separator orientation="vertical" className="h-4" />
        <span className="capitalize">{currentSide}</span>
        <Separator orientation="vertical" className="h-4" />
        <span>{formatDimensions(currentCabinet)}</span>
        <Separator orientation="vertical" className="h-4" />
        <span>{els.length} element{els.length !== 1 ? 's' : ''}</span>
      </div>

      <div className="flex items-center gap-2">
        <span>Zoom</span>
        <Select value={String(zoomLevel)} onValueChange={v => setZoom(Number(v))}>
          <SelectTrigger className="h-6 w-20 text-xs">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {ZOOM_LEVELS.map(z => (
              <SelectItem key={z} value={String(z)}>{Math.round(z * 100)}%</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>
    </div>
  );
}
