// reference/sveltekit-app/src/lib/components/ElementList.svelte
<script lang="ts">
  import { configurator } from '$lib/stores/configurator';

  const { currentElements, selectedId, currentSide } = configurator;
</script>

<div class="flex-1 overflow-auto p-4">
  <h3 class="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">
    Elements — <span class="capitalize">{$currentSide}</span>
    <span class="text-slate-400 ml-1">({$currentElements.length})</span>
  </h3>

  {#if $currentElements.length === 0}
    <p class="text-xs text-slate-400 mt-2">No elements on this side.<br/>Select a tool and click on the panel.</p>
  {:else}
    <ul class="space-y-1">
      {#each $currentElements as el (el.id)}
        <li>
          <button
            class="w-full text-left px-2 py-1.5 rounded text-xs flex items-center gap-2 transition-colors"
            class:bg-blue-50={$selectedId === el.id}
            class:text-blue-700={$selectedId === el.id}
            class:hover:bg-slate-50={$selectedId !== el.id}
            class:text-slate-600={$selectedId !== el.id}
            on:click={() => configurator.selectElement(el.id)}
          >
            <span class="w-2 h-2 rounded-full shrink-0"
              class:bg-amber-400={el.type === 'hole'}
              class:bg-sky-400={el.type === 'rect'}
              class:bg-emerald-400={el.type === 'opening'}
            ></span>
            <span class="capitalize font-medium">{el.type}</span>
            <span class="text-slate-400 ml-auto">{el.x},{el.y}</span>
          </button>
        </li>
      {/each}
    </ul>
  {/if}
</div>

// reference/nextjs-shadcn-babylon/components/element-list.tsx
'use client';

import { useConfiguratorStore } from '@/store/configurator-store';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { CircleDot, Square, RectangleHorizontal } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function ElementList() {
  const { currentSide, selectedElId, selectElement, currentElements } = useConfiguratorStore();
  const els = currentElements();

  const typeIcon = (type: string) => {
    switch (type) {
      case 'hole': return <CircleDot className="h-3 w-3 text-amber-500" />;
      case 'rect': return <Square className="h-3 w-3 text-sky-500" />;
      case 'opening': return <RectangleHorizontal className="h-3 w-3 text-emerald-500" />;
      default: return null;
    }
  };

  return (
    <div className="flex-1 overflow-auto p-3">
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
          Elements
        </h3>
        <Badge variant="secondary" className="text-[10px]">
          <span className="capitalize">{currentSide}</span> • {els.length}
        </Badge>
      </div>

      {els.length === 0 ? (
        <p className="text-xs text-muted-foreground mt-4 text-center">
          No elements yet.<br />Select a tool and click the panel.
        </p>
      ) : (
        <div className="space-y-0.5">
          {els.map(el => (
            <Button
              key={el.id}
              variant="ghost"
              size="sm"
              className={cn(
                'w-full justify-start h-8 px-2 gap-2 text-xs font-normal',
                selectedElId === el.id && 'bg-accent text-accent-foreground'
              )}
              onClick={() => selectElement(el.id)}
            >
              {typeIcon(el.type)}
              <span className="capitalize">{el.type}</span>
              <span className="text-muted-foreground ml-auto font-mono text-[10px]">{el.x},{el.y}</span>
            </Button>
          ))}
        </div>
      )}
    </div>
  );
}
