// reference/sveltekit-app/src/routes/configure/+page.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { configurator } from '$lib/stores/configurator';
  import AppHeader from '$lib/components/AppHeader.svelte';
  import Cabinet3DPreview from '$lib/components/Cabinet3DPreview.svelte';
  import SidePills from '$lib/components/SidePills.svelte';
  import EditorToolbar from '$lib/components/EditorToolbar.svelte';
  import PanelEditor from '$lib/components/PanelEditor.svelte';
  import PropertiesPanel from '$lib/components/PropertiesPanel.svelte';
  import ElementList from '$lib/components/ElementList.svelte';
  import EditorFooter from '$lib/components/EditorFooter.svelte';
  import Toast from '$lib/components/Toast.svelte';
  import { ELEMENT_DEFAULTS, snap,  getPanelDimensions } from '$lib/constants';
  import { get } from 'svelte/store';

  const { tool, currentSide, cabinet, selectedId } = configurator;

  function handleKeydown(e: KeyboardEvent) {
    const tag = (e.target as HTMLElement).tagName;
    if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;

    if (e.ctrlKey || e.metaKey) {
      if (e.key === 'z') { e.preventDefault(); configurator.undo(); }
      if (e.key === 'y') { e.preventDefault(); configurator.redo(); }
      return;
    }

    switch (e.key.toLowerCase()) {
      case 'v': case 'm': configurator.setTool('move'); break;
      case 'h': configurator.setTool('hole'); break;
      case 'r': configurator.setTool('rect'); break;
      case 'o': configurator.setTool('opening'); break;
      case 'delete': case 'backspace': {
        const sel = get(selectedId);
        if (sel) configurator.deleteElement(sel);
        break;
      }
    }
  }

  onMount(() => { window.addEventListener('keydown', handleKeydown); });
  onDestroy(() => { if (typeof window !== 'undefined') window.removeEventListener('keydown', handleKeydown); });
</script>

<svelte:head>
  <title>Cabinet Configurator — SvelteKit</title>
</svelte:head>

<div class="min-h-screen flex flex-col bg-slate-50">
  <AppHeader />

  <main class="flex-1 flex overflow-hidden">
    <!-- Left sidebar: 3D Preview + Side Pills -->
    <aside class="w-72 border-r border-slate-200 bg-white flex flex-col">
      <Cabinet3DPreview />
      <SidePills />
      <ElementList />
    </aside>

    <!-- Center: Toolbar + Panel Editor -->
    <section class="flex-1 flex flex-col">
      <EditorToolbar />
      <PanelEditor />
      <EditorFooter />
    </section>

    <!-- Right sidebar: Properties -->
    <aside class="w-72 border-l border-slate-200 bg-white">
      <PropertiesPanel />
    </aside>
  </main>

  <Toast />
</div>

// reference/nextjs-app/app/configure/page.tsx
'use client';

import AppHeader from '@/components/app-header';
import Cabinet3DPreview from '@/components/cabinet-3d-preview';
import SidePills from '@/components/side-pills';
import EditorToolbar from '@/components/editor-toolbar';
import PanelEditor from '@/components/panel-editor';
import PropertiesPanel from '@/components/properties-panel';
import ElementList from '@/components/element-list';
import EditorFooter from '@/components/editor-footer';
import Toast from '@/components/toast';
import { useConfiguratorStore } from '@/store/configurator-store';
import { useKeyboardShortcuts } from '@/hooks/use-keyboard-shortcuts';

export default function ConfigurePage() {
  useKeyboardShortcuts();
  const currentSide = useConfiguratorStore(s => s.currentSide);
  const clearCurrentSide = useConfiguratorStore(s => s.clearCurrentSide);

  return (
    <div className="h-screen flex flex-col overflow-hidden">
      <AppHeader />
      <div className="flex flex-1 min-h-0">
        {/* Left: 3D Preview */}
        <div className="flex-1 flex flex-col">
          <Cabinet3DPreview />
          <SidePills />
        </div>

        {/* Divider */}
        <div className="w-px bg-gray-200" />

        {/* Right: 2D Editor */}
        <div className="w-[480px] flex flex-col bg-white">
          {/* Editor header */}
          <div className="px-4 py-3 border-b border-gray-200 flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <h2 className="text-[15px] font-semibold">Panel Editor</h2>
              <span className="text-[10px] font-semibold uppercase tracking-wider bg-indigo-50 text-indigo-500 px-2 py-0.5 rounded">
                {currentSide.toUpperCase()}
              </span>
            </div>
            <button
              onClick={clearCurrentSide}
              className="text-[11px] text-gray-500 hover:text-gray-900 hover:bg-gray-100 px-2 py-1 rounded transition-all"
            >
              Clear All
            </button>
          </div>

          <EditorToolbar />
          <PanelEditor />
          <PropertiesPanel />
          <ElementList />
          <EditorFooter />
        </div>
      </div>
      <Toast />
    </div>
  );
}
