// reference/nuxt-vuetify/pages/configure.vue
<template>
  <v-layout class="fill-height">
    <v-app-bar density="compact" flat class="border-b">
      <AppHeader />
    </v-app-bar>

    <v-main class="bg-background">
      <v-container fluid class="pa-0 fill-height">
        <v-row no-gutters class="fill-height">
          <!-- Left sidebar: Side pills -->
          <v-col cols="auto" class="d-flex align-center justify-center" style="width:64px">
            <SidePills />
          </v-col>

          <!-- Center area: toolbar + 3D + editor -->
          <v-col class="d-flex flex-column fill-height">
            <EditorToolbar />

            <div class="flex-grow-1 d-flex" style="min-height:0">
              <!-- 3D preview -->
              <div class="d-flex align-center justify-center" style="width:280px;min-width:200px">
                <Cabinet3DPreview />
              </div>

              <!-- 2D Panel editor -->
              <div class="flex-grow-1 d-flex flex-column" style="min-width:0">
                <PanelEditor />
                <EditorFooter />
              </div>
            </div>
          </v-col>

          <!-- Right sidebar: properties + element list -->
          <v-col cols="auto" style="width:280px" class="border-l d-flex flex-column fill-height bg-surface">
            <PropertiesPanel />
            <v-divider />
            <ElementList />
          </v-col>
        </v-row>
      </v-container>
    </v-main>
  </v-layout>
</template>

<script setup lang="ts">
import { useKeyboardShortcuts } from '~/composables/useKeyboardShortcuts';
useKeyboardShortcuts();
</script>

// reference/nextjs-shadcn-babylon/app/configure/page.tsx
'use client';

import dynamic from 'next/dynamic';
import { useKeyboardShortcuts } from '@/hooks/use-keyboard-shortcuts';
import AppHeader from '@/components/app-header';
import SidePills from '@/components/side-pills';
import EditorToolbar from '@/components/editor-toolbar';
import PanelEditor from '@/components/panel-editor';
import PropertiesPanel from '@/components/properties-panel';
import ElementList from '@/components/element-list';
import EditorFooter from '@/components/editor-footer';
import AppToast from '@/components/app-toast';

const Cabinet3DScene = dynamic(() => import('@/components/cabinet-3d-scene'), { ssr: false });

export default function ConfigurePage() {
  useKeyboardShortcuts();

  return (
    <div className="h-screen flex flex-col bg-background">
      <AppHeader />
      <div className="flex-1 flex overflow-hidden">
        {/* Left panel: 3D + Sides + Element list */}
        <aside className="w-80 border-r flex flex-col bg-card">
          <div className="h-60 border-b">
            <Cabinet3DScene />
          </div>
          <SidePills />
          <ElementList />
        </aside>

        {/* Center: Toolbar + Editor */}
        <section className="flex-1 flex flex-col">
          <EditorToolbar />
          <PanelEditor />
          <EditorFooter />
        </section>

        {/* Right panel: Properties */}
        <aside className="w-80 border-l bg-card">
          <PropertiesPanel />
        </aside>
      </div>
      <AppToast />
    </div>
  );
}
